# Generated by Django 2.2.4 on 2019-09-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utmmetka.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Utmmetka.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Firstvar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_campaign', models.CharField(max_length=300, null=True)),
                ('utm_term', models.CharField(max_length=300, null=True)),
                ('utm_content', models.CharField(max_length=300, null=True)),
                ('utmname', models.CharField(max_length=300, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utmmetka.Person')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Utmmetka.Country'),
        ),
    ]
