# Generated by Django 2.2.4 on 2019-09-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(max_length=50)),
                ('success', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('complete', models.CharField(max_length=500)),
                ('heshteg', models.CharField(max_length=50)),
            ],
        ),
    ]
